# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class GetSolutionError(str, Enum):
    """
    Failed to retrieve the solution
    """

    """
    allowed enum values
    """
    INVALIDMATCHID = 'InvalidMatchId'
    INVALIDPARTICIPANTID = 'InvalidParticipantId'
    TRIALNOTFOUND = 'TrialNotFound'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of GetSolutionError from a JSON string"""
        return cls(json.loads(json_str))


