# coding: utf-8

"""
    OptHub REST API

    OptHubの公開REST APIです。

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ParticipantType(str, Enum):
    """
    参加者の種別
    """

    """
    allowed enum values
    """
    USER = 'User'
    TEAM = 'Team'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ParticipantType from a JSON string"""
        return cls(json.loads(json_str))


