# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from opthub_api_client.models.participant import Participant
from typing import Optional, Set
from typing_extensions import Self

class Solution(BaseModel):
    """
    解
    """ # noqa: E501
    match_id: StrictStr = Field(description="Match ID", alias="matchId")
    participant: Participant
    trial_no: StrictInt = Field(description="Trial number", alias="trialNo")
    variable: List[Union[StrictFloat, StrictInt]] = Field(description="Solution space variable")
    created_at: datetime = Field(description="Creation date and time", alias="createdAt")
    user_id: Optional[StrictStr] = Field(default=None, description="ID of the user who created it", alias="userId")
    __properties: ClassVar[List[str]] = ["matchId", "participant", "trialNo", "variable", "createdAt", "userId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Solution from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of participant
        if self.participant:
            _dict['participant'] = self.participant.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Solution from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "matchId": obj.get("matchId"),
            "participant": Participant.from_dict(obj["participant"]) if obj.get("participant") is not None else None,
            "trialNo": obj.get("trialNo"),
            "variable": obj.get("variable"),
            "createdAt": obj.get("createdAt"),
            "userId": obj.get("userId")
        })
        return _obj


