# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.participant_type import ParticipantType

class TestParticipantType(unittest.TestCase):
    """ParticipantType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testParticipantType(self):
        """Test ParticipantType"""
        # inst = ParticipantType()

if __name__ == '__main__':
    unittest.main()
