# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.api.alias_api import AliasApi


class TestAliasApi(unittest.TestCase):
    """AliasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AliasApi()

    def tearDown(self) -> None:
        pass

    def test_resolve_competition_alias_by_id(self) -> None:
        """Test case for resolve_competition_alias_by_id

        Retrieve the competition alias from the competition ID
        """
        pass

    def test_resolve_competition_id_by_alias(self) -> None:
        """Test case for resolve_competition_id_by_alias

        Retrieve the competition ID from the competition alias
        """
        pass

    def test_resolve_match_alias_by_id(self) -> None:
        """Test case for resolve_match_alias_by_id

        Retrieve the match alias from the match ID
        """
        pass

    def test_resolve_match_id_by_alias(self) -> None:
        """Test case for resolve_match_id_by_alias

        Retrieve the match ID from the match alias
        """
        pass


if __name__ == '__main__':
    unittest.main()
