# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.server_error_code import ServerErrorCode

class TestServerErrorCode(unittest.TestCase):
    """ServerErrorCode unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testServerErrorCode(self):
        """Test ServerErrorCode"""
        # inst = ServerErrorCode()

if __name__ == '__main__':
    unittest.main()
