# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.api.match_trials_api import MatchTrialsApi


class TestMatchTrialsApi(unittest.TestCase):
    """MatchTrialsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MatchTrialsApi()

    def tearDown(self) -> None:
        pass

    def test_create_match_trial(self) -> None:
        """Test case for create_match_trial

        Create a match trial
        """
        pass

    def test_get_match_evaluation(self) -> None:
        """Test case for get_match_evaluation

        Retrieve status of a specific match evaluation related to the Solution submitted by the Participant themselves.
        """
        pass

    def test_get_match_score(self) -> None:
        """Test case for get_match_score

        Retrieve status of a specific match score related to the Solution submitted by the Participant themselves.
        """
        pass

    def test_get_match_trial(self) -> None:
        """Test case for get_match_trial

        Retrieve status of a specific Match Trial related to the Solution submitted by the Participant themselves.
        """
        pass

    def test_get_solution(self) -> None:
        """Test case for get_solution

        Retrieve the Solution submitted by the Participant themselves.
        """
        pass


if __name__ == '__main__':
    unittest.main()
