# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.create_match_trial400_response import CreateMatchTrial400Response

class TestCreateMatchTrial400Response(unittest.TestCase):
    """CreateMatchTrial400Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CreateMatchTrial400Response:
        """Test CreateMatchTrial400Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CreateMatchTrial400Response`
        """
        model = CreateMatchTrial400Response()
        if include_optional:
            return CreateMatchTrial400Response(
                code = 'InvalidBodyFormat',
                message = 'Invalid body format.'
            )
        else:
            return CreateMatchTrial400Response(
        )
        """

    def testCreateMatchTrial400Response(self):
        """Test CreateMatchTrial400Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
