# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.2.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.runner_status import RunnerStatus

class TestRunnerStatus(unittest.TestCase):
    """RunnerStatus unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testRunnerStatus(self):
        """Test RunnerStatus"""
        # inst = RunnerStatus()

if __name__ == '__main__':
    unittest.main()
