# coding: utf-8

"""
    OptHub REST API

    OptHubの公開REST APIです。

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.api.solution_api import SolutionApi


class TestSolutionApi(unittest.TestCase):
    """SolutionApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SolutionApi()

    def tearDown(self) -> None:
        pass

    def test_create_solution(self) -> None:
        """Test case for create_solution

        解の作成
        """
        pass

    def test_get_solution(self) -> None:
        """Test case for get_solution

        解の取得
        """
        pass


if __name__ == '__main__':
    unittest.main()
