# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.scalar_or_vector import ScalarOrVector

class TestScalarOrVector(unittest.TestCase):
    """ScalarOrVector unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ScalarOrVector:
        """Test ScalarOrVector
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ScalarOrVector`
        """
        model = ScalarOrVector()
        if include_optional:
            return ScalarOrVector(
                vector = [1.234,-5.678,9.1011],
                scalar = -12.1314
            )
        else:
            return ScalarOrVector(
        )
        """

    def testScalarOrVector(self):
        """Test ScalarOrVector"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
