# coding: utf-8

"""
    OptHub REST API

    OptHubの公開REST APIです。

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.api.match_api import MatchApi


class TestMatchApi(unittest.TestCase):
    """MatchApi unit test stubs"""

    def setUp(self) -> None:
        self.api = MatchApi()

    def tearDown(self) -> None:
        pass

    def test_resolve_match_alias_by_id(self) -> None:
        """Test case for resolve_match_alias_by_id

        競技IDから競技のエイリアスを取得
        """
        pass

    def test_resolve_match_id_by_alias(self) -> None:
        """Test case for resolve_match_id_by_alias

        競技のエイリアスから競技IDを取得
        """
        pass


if __name__ == '__main__':
    unittest.main()
