# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.1
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.get_solution_error import GetSolutionError

class TestGetSolutionError(unittest.TestCase):
    """GetSolutionError unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testGetSolutionError(self):
        """Test GetSolutionError"""
        # inst = GetSolutionError()

if __name__ == '__main__':
    unittest.main()
