# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.match_trial_response import MatchTrialResponse

class TestMatchTrialResponse(unittest.TestCase):
    """MatchTrialResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> MatchTrialResponse:
        """Test MatchTrialResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `MatchTrialResponse`
        """
        model = MatchTrialResponse()
        if include_optional:
            return MatchTrialResponse(
                trial_no = 4,
                status = 'evaluating',
                created_at = '2024-08-06T10:11:45.789Z'
            )
        else:
            return MatchTrialResponse(
                trial_no = 4,
                status = 'evaluating',
                created_at = '2024-08-06T10:11:45.789Z',
        )
        """

    def testMatchTrialResponse(self):
        """Test MatchTrialResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
