# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.get_solution404_response import GetSolution404Response

class TestGetSolution404Response(unittest.TestCase):
    """GetSolution404Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetSolution404Response:
        """Test GetSolution404Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetSolution404Response`
        """
        model = GetSolution404Response()
        if include_optional:
            return GetSolution404Response(
                code = 'MatchNotFound',
                message = 'Match is not found.'
            )
        else:
            return GetSolution404Response(
        )
        """

    def testGetSolution404Response(self):
        """Test GetSolution404Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
