# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.2.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.api.trial_api import TrialApi


class TestTrialApi(unittest.TestCase):
    """TrialApi unit test stubs"""

    def setUp(self) -> None:
        self.api = TrialApi()

    def tearDown(self) -> None:
        pass

    def test_get_match_trial(self) -> None:
        """Test case for get_match_trial

        Retrieve status of a specific Trial related to the Solution submitted by the Participant themselves.
        """
        pass


if __name__ == '__main__':
    unittest.main()
