# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.get_match_trial403_response import GetMatchTrial403Response

class TestGetMatchTrial403Response(unittest.TestCase):
    """GetMatchTrial403Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetMatchTrial403Response:
        """Test GetMatchTrial403Response
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetMatchTrial403Response`
        """
        model = GetMatchTrial403Response()
        if include_optional:
            return GetMatchTrial403Response(
                code = 'CompetitionNotStarted',
                message = 'Competition is not started.'
            )
        else:
            return GetMatchTrial403Response(
        )
        """

    def testGetMatchTrial403Response(self):
        """Test GetMatchTrial403Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
