# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.server_error_response import ServerErrorResponse

class TestServerErrorResponse(unittest.TestCase):
    """ServerErrorResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServerErrorResponse:
        """Test ServerErrorResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServerErrorResponse`
        """
        model = ServerErrorResponse()
        if include_optional:
            return ServerErrorResponse(
                code = 'UnexpectedServerError',
                message = 'Unexpected server error.'
            )
        else:
            return ServerErrorResponse(
        )
        """

    def testServerErrorResponse(self):
        """Test ServerErrorResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
