# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.participant import Participant

class TestParticipant(unittest.TestCase):
    """Participant unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Participant:
        """Test Participant
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Participant`
        """
        model = Participant()
        if include_optional:
            return Participant(
                participant_id = '912f548d-2bbe-48ab-90ce-e96dae38377d',
                participant_type = 'User'
            )
        else:
            return Participant(
                participant_id = '912f548d-2bbe-48ab-90ce-e96dae38377d',
                participant_type = 'User',
        )
        """

    def testParticipant(self):
        """Test Participant"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
