# coding: utf-8

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.2.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from opthub_api_client.models.match_trial_status_type import MatchTrialStatusType

class TestMatchTrialStatusType(unittest.TestCase):
    """MatchTrialStatusType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMatchTrialStatusType(self):
        """Test MatchTrialStatusType"""
        # inst = MatchTrialStatusType()

if __name__ == '__main__':
    unittest.main()
