# coding: utf-8

# flake8: noqa

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.1.0
    Contact: dev@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "1.0.0"

# import apis into sdk package
from opthub_api_client.api.alias_api import AliasApi
from opthub_api_client.api.competition_api import CompetitionApi
from opthub_api_client.api.match_api import MatchApi
from opthub_api_client.api.solution_api import SolutionApi

# import ApiClient
from opthub_api_client.api_response import ApiResponse
from opthub_api_client.api_client import ApiClient
from opthub_api_client.configuration import Configuration
from opthub_api_client.exceptions import OpenApiException
from opthub_api_client.exceptions import ApiTypeError
from opthub_api_client.exceptions import ApiValueError
from opthub_api_client.exceptions import ApiKeyError
from opthub_api_client.exceptions import ApiAttributeError
from opthub_api_client.exceptions import ApiException

# import models into sdk package
from opthub_api_client.models.create_solution_response import CreateSolutionResponse
from opthub_api_client.models.get_solution_error import GetSolutionError
from opthub_api_client.models.participant import Participant
from opthub_api_client.models.participant_type import ParticipantType
from opthub_api_client.models.solution import Solution
