# coding: utf-8

# flake8: noqa

"""
    OptHub REST API

    OptHub Public REST API.

    The version of the OpenAPI document: 0.3.0
    Contact: competition@opthub.ai
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


__version__ = "0.3.0"

# Define package exports
__all__ = [
    "MatchTrialsApi",
    "ApiResponse",
    "ApiClient",
    "Configuration",
    "OpenApiException",
    "ApiTypeError",
    "ApiValueError",
    "ApiKeyError",
    "ApiAttributeError",
    "ApiException",
    "AuthErrorCode",
    "AuthErrorResponse",
    "CreateMatchTrial400Response",
    "CreateMatchTrial403Response",
    "CreateMatchTrial404Response",
    "CreateMatchTrialRequest",
    "GetMatchEvaluation404Response",
    "GetMatchScore404Response",
    "GetMatchTrial403Response",
    "GetMatchTrial404Response",
    "GetSolution404Response",
    "MatchTrialEvaluation",
    "MatchTrialResponse",
    "MatchTrialScore",
    "MatchTrialStatus",
    "RunnerStatus",
    "ScalarOrVector",
    "ServerErrorCode",
    "ServerErrorResponse",
    "Solution",
]

# import apis into sdk package
from opthub_api_client.api.match_trials_api import MatchTrialsApi as MatchTrialsApi

# import ApiClient
from opthub_api_client.api_response import ApiResponse as ApiResponse
from opthub_api_client.api_client import ApiClient as ApiClient
from opthub_api_client.configuration import Configuration as Configuration
from opthub_api_client.exceptions import OpenApiException as OpenApiException
from opthub_api_client.exceptions import ApiTypeError as ApiTypeError
from opthub_api_client.exceptions import ApiValueError as ApiValueError
from opthub_api_client.exceptions import ApiKeyError as ApiKeyError
from opthub_api_client.exceptions import ApiAttributeError as ApiAttributeError
from opthub_api_client.exceptions import ApiException as ApiException

# import models into sdk package
from opthub_api_client.models.auth_error_code import AuthErrorCode as AuthErrorCode
from opthub_api_client.models.auth_error_response import AuthErrorResponse as AuthErrorResponse
from opthub_api_client.models.create_match_trial400_response import CreateMatchTrial400Response as CreateMatchTrial400Response
from opthub_api_client.models.create_match_trial403_response import CreateMatchTrial403Response as CreateMatchTrial403Response
from opthub_api_client.models.create_match_trial404_response import CreateMatchTrial404Response as CreateMatchTrial404Response
from opthub_api_client.models.create_match_trial_request import CreateMatchTrialRequest as CreateMatchTrialRequest
from opthub_api_client.models.get_match_evaluation404_response import GetMatchEvaluation404Response as GetMatchEvaluation404Response
from opthub_api_client.models.get_match_score404_response import GetMatchScore404Response as GetMatchScore404Response
from opthub_api_client.models.get_match_trial403_response import GetMatchTrial403Response as GetMatchTrial403Response
from opthub_api_client.models.get_match_trial404_response import GetMatchTrial404Response as GetMatchTrial404Response
from opthub_api_client.models.get_solution404_response import GetSolution404Response as GetSolution404Response
from opthub_api_client.models.match_trial_evaluation import MatchTrialEvaluation as MatchTrialEvaluation
from opthub_api_client.models.match_trial_response import MatchTrialResponse as MatchTrialResponse
from opthub_api_client.models.match_trial_score import MatchTrialScore as MatchTrialScore
from opthub_api_client.models.match_trial_status import MatchTrialStatus as MatchTrialStatus
from opthub_api_client.models.runner_status import RunnerStatus as RunnerStatus
from opthub_api_client.models.scalar_or_vector import ScalarOrVector as ScalarOrVector
from opthub_api_client.models.server_error_code import ServerErrorCode as ServerErrorCode
from opthub_api_client.models.server_error_response import ServerErrorResponse as ServerErrorResponse
from opthub_api_client.models.solution import Solution as Solution

